Executing script: /Users/geoffarner/Desktop/Actualize/twilio-quest/functions.py
Script arguments: 
Output:
Traceback (most recent call last):
  File "/Users/geoffarner/Desktop/Actualize/twilio-quest/functions.py", line 18, in <module>
    first_number = (sys.argv[1])
IndexError: list index out of range

